"""Direct material-library builds backed by the source KG compiler."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from kgtracevis.service.kg_construction import (
    DEFAULT_SOURCE_KG_BUILD_DIR,
    KGConstructionBuildResponse,
    run_kg_construction_build,
    safe_output_name,
)
from kgtracevis.service.kg_materials import (
    KGMaterialDirectBuildRequest,
    extract_kg_material_to_structured_records,
    get_kg_material,
    prepare_kg_material_construction_build,
)


class KGMaterialBuildResponse(BaseModel):
    """Response envelope for a direct material-library source KG compiler build."""

    model_config = ConfigDict(extra="forbid")

    status: Literal["built"] = "built"
    run_id: str
    output_dir: str
    nodes_path: str
    edges_path: str
    summary_path: str
    manifest_path: str
    source_library_manifest_path: str | None = None
    draft_manifest_path: str | None = None
    profile_manifest_path: str | None = None
    rca_view_manifest_path: str | None = None
    artifacts: dict[str, str] = Field(default_factory=dict)
    summary: dict[str, Any]
    material_root: str
    material_ids: list[str]
    materials: list[dict[str, Any]]
    source_ids: list[str]
    compiler_build: dict[str, Any]
    claim_boundary: str = (
        "material-derived KG rows are generated by source_kg_compiler; they do "
        "not use the removed legacy construction/review/publish pipeline"
    )


def run_kg_material_build(
    request: KGMaterialDirectBuildRequest,
    *,
    output_root: Path | None = None,
    material_root: Path | None = None,
) -> KGMaterialBuildResponse:
    """Compile selected source materials with the current source KG compiler."""
    if request.extraction_mode in {"missing", "always"}:
        extraction_request = request.extraction_request
        for material_id in request.material_ids:
            material = get_kg_material(material_id, material_root=material_root).material
            if request.extraction_mode == "always" or not material.is_build_ready:
                extract_kg_material_to_structured_records(
                    material_id,
                    extraction_request or request.extraction_request or _default_extract_request(),
                    material_root=material_root,
                )

    build_sources = prepare_kg_material_construction_build(
        request,
        material_root=material_root,
    )
    output_dir = (output_root or DEFAULT_SOURCE_KG_BUILD_DIR) / safe_output_name(
        request.output_name
    )
    compiler_result = run_kg_construction_build(
        build_sources.construction_request,
        build_root=output_dir.parent,
    )
    return _material_build_response(
        request=request,
        build_sources=build_sources,
        compiler_result=compiler_result,
    )


def _default_extract_request():
    from kgtracevis.service.kg_materials import KGMaterialExtractionRunRequest

    return KGMaterialExtractionRunRequest(overwrite=True)


def _material_build_response(
    *,
    request: KGMaterialDirectBuildRequest,
    build_sources,
    compiler_result: KGConstructionBuildResponse,
) -> KGMaterialBuildResponse:
    artifacts = {
        "nodes": compiler_result.nodes_path,
        "edges": compiler_result.edges_path,
        "summary": compiler_result.summary_path,
        "manifest": compiler_result.manifest_path,
    }
    return KGMaterialBuildResponse(
        run_id=compiler_result.run_id,
        output_dir=compiler_result.output_dir,
        nodes_path=compiler_result.nodes_path,
        edges_path=compiler_result.edges_path,
        summary_path=compiler_result.summary_path,
        manifest_path=compiler_result.manifest_path,
        source_library_manifest_path=compiler_result.source_library_manifest_path,
        draft_manifest_path=compiler_result.draft_manifest_path,
        profile_manifest_path=compiler_result.profile_manifest_path,
        rca_view_manifest_path=compiler_result.rca_view_manifest_path,
        artifacts=artifacts,
        summary=compiler_result.summary,
        material_root=build_sources.material_root,
        material_ids=list(request.material_ids),
        materials=[material.model_dump(mode="json") for material in build_sources.materials],
        source_ids=[source.source_id for source in build_sources.sources],
        compiler_build=compiler_result.model_dump(mode="json"),
    )
