"""Source-constrained KG construction modules."""

from kgtracevis.kg_construction.alignment import (
    AlignmentCandidate,
    AlignmentIssueRecord,
    AlignmentResult,
    CanonicalEntityEntry,
    run_entity_alignment,
)
from kgtracevis.kg_construction.audit_graph import SourceAuditGraph
from kgtracevis.kg_construction.candidate_entity_extractor import (
    CandidateEntity,
    extract_candidate_entities,
)
from kgtracevis.kg_construction.candidate_triple_extractor import (
    CandidateTriple,
    extract_candidate_triples,
)
from kgtracevis.kg_construction.case_kg_hardening import (
    CandidateKGOutput,
    CaseAuditRow,
    audit_mvtec_cases,
    audit_wm811k_cases,
    build_candidate_kg,
    build_coverage_report,
    run_before_after_comparison,
    validate_candidate_claim_boundaries,
    write_candidate_kg_artifacts,
    write_case_audit_artifacts,
    write_edge_review_queue,
)
from kgtracevis.kg_construction.confidence_assigner import assign_confidence, edge_weight
from kgtracevis.kg_construction.draft import (
    DraftEntity,
    DraftKG,
    DraftRelation,
    KGConstructionSource,
    draft_entity_to_kg_node,
    draft_relation_to_kg_edge,
    draft_relations_from_source_text,
    draft_status_to_review_status,
)
from kgtracevis.kg_construction.end_to_end_interpretability_audit import (
    EndToEndInterpretabilityAuditOutput,
    write_end_to_end_interpretability_audit,
)
from kgtracevis.kg_construction.export_kg_csv import (
    export_edges_csv,
    export_kg_csv,
    export_nodes_csv,
    validate_edges,
    validate_kg_csv_contract,
    validate_nodes,
)
from kgtracevis.kg_construction.extractors import (
    ExtractorRegistry,
    KGSourceExtractor,
    LLMDocumentIEExtractor,
    OfflineDocumentIEExtractor,
    ParsedKGSourceExtractor,
    StructuredRecordExtractor,
    TepRcaGraphExtractor,
    TepSemanticLiftExtractor,
    TepVariableMappingExtractor,
    default_extractor_registry,
    extract_source_draft,
)
from kgtracevis.kg_construction.models import (
    KGConstructionBuildSummary,
    KGConstructionDraftRow,
    KGConstructionManifest,
    KGConstructionReviewDecision,
    KGConstructionRunRecord,
    build_construction_manifest,
    build_construction_summary,
    build_kg_construction_run_id,
    build_review_decision_id,
    draft_rows_from_draft,
    review_decision_for_edge,
    review_decision_for_item,
)
from kgtracevis.kg_construction.mvtec_source_bundle import (
    DEFAULT_MVTEC_SOURCE_DIR,
    DEFAULT_MVTEC_SOURCES,
    DownloadableSource,
    download_mvtec_source_bundle,
)
from kgtracevis.kg_construction.pipeline import KGConstructionResult, run_kg_construction
from kgtracevis.kg_construction.profiles import (
    GENERIC_PROFILE,
    TEP_PROFILE,
    RcaProfile,
    profile_for_scenario,
)
from kgtracevis.kg_construction.publish import (
    PublishManifest,
    PublishReportItem,
    PublishSnapshot,
    append_review_decision,
    build_publish_snapshot,
    load_review_decisions,
    write_publish_snapshot,
)
from kgtracevis.kg_construction.qa import KGQAFinding, KGQAReport, run_kg_qa
from kgtracevis.kg_construction.rca_view import (
    RcaReasoningView,
    build_rca_reasoning_view,
)
from kgtracevis.kg_construction.review_queue import (
    ReviewQueueItem,
    build_review_queue,
    review_queue_payload,
)
from kgtracevis.kg_construction.semantic_projection import (
    SemanticLayerResult,
    project_semantic_layer,
)
from kgtracevis.kg_construction.source_loader import (
    SourceRecord,
    load_source_registry,
    load_source_text,
    load_structured_records,
)
from kgtracevis.kg_construction.sources import (
    SourceLibraryRecord,
    load_source_library,
    source_library_records_from_construction_sources,
    write_source_library_manifest,
)
from kgtracevis.kg_construction.tep_import import tep_external_id_to_kg_id
from kgtracevis.kg_construction.triple_cleaner import (
    clean_candidate_nodes,
    clean_candidate_triples,
    clean_kg_edges,
    clean_kg_nodes,
)

__all__ = [
    "CandidateEntity",
    "CandidateKGOutput",
    "CandidateTriple",
    "CaseAuditRow",
    "DEFAULT_MVTEC_SOURCES",
    "DEFAULT_MVTEC_SOURCE_DIR",
    "DownloadableSource",
    "DraftEntity",
    "DraftKG",
    "DraftRelation",
    "EndToEndInterpretabilityAuditOutput",
    "ExtractorRegistry",
    "GENERIC_PROFILE",
    "AlignmentCandidate",
    "AlignmentIssueRecord",
    "AlignmentResult",
    "CanonicalEntityEntry",
    "KGConstructionResult",
    "KGConstructionBuildSummary",
    "KGConstructionDraftRow",
    "KGConstructionManifest",
    "KGConstructionReviewDecision",
    "KGConstructionRunRecord",
    "KGConstructionSource",
    "KGQAFinding",
    "KGQAReport",
    "KGSourceExtractor",
    "LLMDocumentIEExtractor",
    "OfflineDocumentIEExtractor",
    "ParsedKGSourceExtractor",
    "RcaProfile",
    "RcaReasoningView",
    "ReviewQueueItem",
    "SemanticLayerResult",
    "SourceAuditGraph",
    "SourceLibraryRecord",
    "SourceRecord",
    "PublishManifest",
    "PublishReportItem",
    "PublishSnapshot",
    "StructuredRecordExtractor",
    "TEP_PROFILE",
    "TepRcaGraphExtractor",
    "TepSemanticLiftExtractor",
    "TepVariableMappingExtractor",
    "assign_confidence",
    "append_review_decision",
    "audit_mvtec_cases",
    "audit_wm811k_cases",
    "build_construction_manifest",
    "build_construction_summary",
    "build_candidate_kg",
    "build_kg_construction_run_id",
    "build_review_decision_id",
    "build_coverage_report",
    "build_rca_reasoning_view",
    "build_publish_snapshot",
    "build_review_queue",
    "clean_candidate_nodes",
    "clean_candidate_triples",
    "clean_kg_edges",
    "clean_kg_nodes",
    "default_extractor_registry",
    "download_mvtec_source_bundle",
    "draft_relations_from_source_text",
    "draft_entity_to_kg_node",
    "draft_relation_to_kg_edge",
    "draft_rows_from_draft",
    "draft_status_to_review_status",
    "edge_weight",
    "export_edges_csv",
    "export_kg_csv",
    "export_nodes_csv",
    "extract_candidate_entities",
    "extract_candidate_triples",
    "extract_source_draft",
    "load_source_registry",
    "load_source_text",
    "load_structured_records",
    "load_source_library",
    "load_review_decisions",
    "profile_for_scenario",
    "project_semantic_layer",
    "review_decision_for_edge",
    "review_decision_for_item",
    "review_queue_payload",
    "run_kg_construction",
    "run_entity_alignment",
    "run_kg_qa",
    "source_library_records_from_construction_sources",
    "run_before_after_comparison",
    "tep_external_id_to_kg_id",
    "validate_candidate_claim_boundaries",
    "validate_edges",
    "validate_kg_csv_contract",
    "validate_nodes",
    "write_candidate_kg_artifacts",
    "write_case_audit_artifacts",
    "write_end_to_end_interpretability_audit",
    "write_edge_review_queue",
    "write_source_library_manifest",
    "write_publish_snapshot",
]
